version: "3.9"
services:
  backend:
    build: . #/backend
    container_name: vigil-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: comp440
      DB_NAME: vigil_iot
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: vigil-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: comp440
      MYSQL_DATABASE: vigil_iot
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: